[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rusqlite = { version = "0.31", features = ["bundled"] }
rand = "0.8"
tera = "1.19"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }